[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[plugins.inputs]
  output_path = "lighthouse-report.html"

[plugins.inputs.settings]
  timeout = 60000  # 60 seconds timeout

[plugins.inputs.thresholds]
  performance = 0.7
  accessibility = 0.8
  "best-practices" = 0.8
  seo = 0.8

# Define the paths to audit
[[plugins.inputs.audits]]
path = "https://lossdisfunction.com/"

[[plugins.inputs.audits]]
path = "https://lossdisfunction.com/about"

[[plugins.inputs.audits]]
path = "https://lossdisfunction.com/archives"

[[plugins.inputs.audits]]
path = "https://lossdisfunction.com/lore"

[[plugins.inputs.audits]]
path = "https://lossdisfunction.com/lexicon"
