[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[plugins.inputs]
  output_path = "lighthouse-report.html"
  timeout = 60000
  urls = ["/", "/about", "/archives", "/lore", "/lexicon"]

[plugins.inputs.thresholds]
  performance = 0.7
  accessibility = 0.8
  "best-practices" = 0.8
  seo = 0.8
